<? $this->headTitle("Управление скидками на сумму корзины") ?>

<div class="admin-content-block">
    <h3>Скидки корзины</h3>
    <br>
    <div id="actions-submenu">
        <h4>Действия</h4>
        <div class="list-group">
            <a class="list-group-item" href="<?= $this->url('catalog/discount/add') ?>"><i class="fas fa-plus"></i> Добавить скидку</a>
        </div>
    </div>


    <div class="table-responsive">
        <table class="table table-hover table-striped table-discounts">
            <colgroup>
                <col class="col-min"/>
                <col class="col-max"/>
                <col class="col-discount"/>
                <col class="col-actions"/>
            </colgroup>
            <thead>
                <tr>
                    <th>Минимальная сумма</th>
                    <th>Максимальная сумма</th>
                    <th>Размер скидки, %</th>
                    <th></th>
                </tr>
            </thead>
            <? foreach ($this->records as $item): ?>
                <tr>
                    <td><?= $item->min ?></td>
                    <td><?= $item->max ?></td>
                    <td><?= $item->discount ?></td>
                    <td>
                        <a href="<?= $this->url('catalog/discount/edit', ['id' => $item->id]) ?>" title="Изменить"><i class="fas fa-pen icon-green"></i></a>
                        <a href="<?= $this->url('catalog/discount/delete', ['id' => $item->id]) ?>" title="Удалить" class="confirm"><i class="fas fa-times icon-red"></i></a>
                    </td>
                </tr>
            <? endforeach ?>
        </table>
    </div>
</div>