<?
/**
 * Copyright (c) 2019.
 *
 * @author Syber
 */

$this->headTitle('Управление отзывами');
$this->inlineScript()->appendScript("window.modules.push('cms/modules/catalog/feedback.admin.list')");
?>

<h2>Управление отзывами</h2>
<br>

<div id="feedbackListApp" class="admin-feedback">
    <table class="table table-sm table-bordered table-hover admin-feedback-list">
        <colgroup>
            <col class="col-date"/>
            <col class="col-username"/>
            <col class="col-item"/>
            <col class="col-rate"/>
            <col class="col-active"/>
            <col class="col-actions"/>
        </colgroup>
        <thead>
            <tr class="table-head">
                <th>
                    <a href="Javascript:void(0)" @click="setOrder('date')">Дата</a><br>
                    <input type="date" class="form-control" style="width: 170px;" v-model="filter.fields.date">
                </th>
                <th>
                    <a href="Javascript:void(0)" @click="setOrder('username')">Пользователь</a><br>
                    <input type="text" class="form-control" v-model="filter.fields.username">
                </th>
                <th>
                    <a href="Javascript:void(0)" @click="setOrder('item')">Товар</a><br>
                    <input type="text" class="form-control" v-model="filter.fields.item">
                </th>
                <th>
                    <a href="Javascript:void(0)" @click="setOrder('rate')">Оценка</a><br>
                    <select class="form-control" v-model="filter.fields.rate">
                        <option value=""></option>
                        <option value="1">1</option>
                        <option value="2">2</option>
                        <option value="3">3</option>
                        <option value="4">4</option>
                        <option value="5">5</option>
                    </select>
                </th>
                <th>
                    <a href="Javascript:void(0)" @click="setOrder('active')">Активен</a><br>
                    <select class="form-control" v-model="filter.fields.active">
                        <option value=""></option>
                        <option value="0">Неактивен</option>
                        <option value="1">Активен</option>
                    </select>
                </th>
                <th><a class="clear-filter" title="Очистить фильтр" @click="clearFilter"><i class="fas fa-times-circle"></i></a></th>
            </tr>
        </thead>
        <tr v-for="feedback in items">
            <td>{{ feedback.format_date }}</td>
            <td>{{ feedback.username }}</td>
            <td><a :href="feedback.link" target="_blank">{{ feedback.item_name }}</a></td>
            <td>
                <div class="rate">
                    <div class="star" v-for="(position, index) in [1, 2, 3, 4, 5]">
                        <img src="/img/rate-gold.png" v-if="position <= feedback.rate">
                        <img src="/img/rate-gray.png" v-else="">
                    </div>
                </div>
            </td>
            <td class="column-active">{{ feedback.active == '1' ? 'Да' : 'Нет' }}</td>
            <td>
                <a :href="'<?= $this->url('catalog/feedback/edit') ?>' + feedback.id" title="Изменить"><i class="fas fa-pen icon-green"></i></a>
                <a href="Javascript:void(0)" @click.prevent="deleteFeedback(feedback.id)" title="Удалить"><i class="fas fa-times icon-red"></i></a>
            </td>
        </tr>
    </table>

    <div class="pages-block">
        <div class="paginator">
            <nav aria-label="Постраничная навигация" v-if="pagination.pages.length > 1">
                <ul class="pagination">
                    <li class="page-item" :class="{ disabled: !pagination.arrows.left }">
                        <a class="page-link" @click="pageDec" href="Javascript:void(0)"><i class="fas fa-arrow-left"></i></a>
                    </li>
                    <li class="page-item" :class="{ 'active' : page == filter.page}" v-for="page in pagination.pages">
                        <a class="page-link" @click="pageSet(page)"  href="Javascript:void(0)">{{ page }} </a>
                    </li>
                    <li class="page-item" :class="{ disabled: !pagination.arrows.right }">
                        <a class="page-link" @click="pageInc" href="Javascript:void(0)"><i class="fas fa-arrow-right"></i></a>
                    </li>
                </ul>
            </nav>
        </div>
        <div class="page-size">
            <label>Записей на странице:</label>
            <select class="form-control" v-model="params.pageSize">
                <option value="50">50</option>
                <option value="100">100</option>
                <option value="100000">Все</option>
            </select>
        </div>
    </div>

</div>