<?
/**
 * Copyright (c) 2019.
 *
 * @author Syber
 */

$this->inlineScript()->appendScript("cms_modules.push('cms/plugins/common.seourl')");
$this->headTitle("Редактирование группы")
?>

<div class="admin-content-block">
    <h3>Редактирование группы</h3>

    <div class="admin-buttons">
        <a class="btn btn-light" href="<?= $this->url('catalog/groups') ?>">Вернуться назад</a>
    </div>

    <?= $this->form($this->form) ?>
</div>