<?
    $this->headTitle("Редактирование купона");
    $this->inlineScript()->appendScript("window.modules.push('cms/modules/catalog/coupons.form')");
?>

<div class="admin-content-block">
    <h3>Редактирование купона</h3>

    <div class="admin-buttons">
        <a class="btn btn-light" href="<?= $this->url('catalog/coupons') ?>">Вернуться назад</a>
    </div>

    <?= $this->form($this->form) ?>
</div>