<? $this->headTitle("Валюта") ?>

<div class="admin-content-block">
    <h3>Валюта</h3>
    <br>
    <div id="actions-submenu">
        <h4>Действия</h4>
        <div class="list-group">
            <a class="list-group-item" href="<?= $this->url('catalog/currencies/add') ?>"><i class="fas fa-plus"></i> Добавить валюту</a>
        </div>
    </div>


    <div class="table-responsive">
        <table class="table table-hover table-striped">
            <thead>
                <tr>
                    <th>Код</th>
                    <th>Название</th>
                    <th>Курс</th>
                    <th style="width: 60px"></th>
                </tr>
            </thead>
            <? foreach ($this->records as $item): ?>
                <tr>
                    <td><?= $item->code ?></td>
                    <td><?= $item->name ?></td>
                    <td><?= $item->course ?></td>
                    <td>
                        <a href="<?= $this->url('catalog/currencies/edit', ['id' => $item->id]) ?>" title="Изменить"><i class="fas fa-pen icon-green"></i></a>
                        <a href="<?= $this->url('catalog/currencies/delete', ['id' => $item->id]) ?>" title="Удалить" class="confirm"><i class="fas fa-times icon-red"></i></a>
                    </td>
                </tr>
            <? endforeach ?>
        </table>
    </div>
</div>