<div id="searchWidget">
    <form action="<?= $this->url('catalog/search') ?>" method="get">
        <div class="input-group mb-3">
            <input type="text" name="query" class="form-control" placeholder="Введите название товара или его артикул">
            <div class="input-group-append">
                <button class="btn btn-outline-secondary" type="submit">Поиск</button>
            </div>
        </div>
    </form>
</div>
