<?
/**
 * Copyright (c) 2019.
 *
 * @author Syber
 */

$this->headTitle("Редактирование значения свойства товара")
?>

<div class="admin-content-block">
    <h3>Редактирование значения свойства товара</h3>

    <div class="admin-buttons">
        <a class="btn btn-light" href="<?= $this->url('catalog/items-properties-defaults/list') ?>">Вернуться назад</a>
    </div>

    <?= $this->form($this->form) ?>
</div>